"""Choose the routing agent's confidence threshold and cue mode on the DEV set only.

Run from the repo root:   uv run python scripts/calibrate_agent_threshold.py

The agent classifies the 40 dev items once (cached), then every threshold and cue mode is scored by
re-running only the deterministic policy step, which costs no further calls. The golden set is never
loaded here.

Writes results/eval/agent_dev_calibration.md and prints the chosen setting, which then goes into
`config.yaml` as `thresholds.intent_confidence`.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from src.config import load_config, resolve  # noqa: E402
from src.contracts import ConversationState, GoldenExample, Intent, SupportRequest, Turn  # noqa: E402
from src.core.prompts import CLASSIFIER_PROMPT_VERSION  # noqa: E402
from src.dataprep.loaders import eval_pool  # noqa: E402
from src.eval.agent_runner import run_agent  # noqa: E402
from src.eval.metrics import evaluate  # noqa: E402
from src.ports.factory import build_deps  # noqa: E402

OUT = ROOT / "results" / "eval" / "agent_dev_calibration.md"
THRESHOLDS = [0.0, 0.5, 0.6, 0.7, 0.8, 0.9]


def dev_examples() -> list[GoldenExample]:
    dev = pd.read_csv(resolve("data/golden/dev_labeling_sheet.csv"), dtype=str, keep_default_na=False)
    pool = eval_pool()
    pool = pool.assign(record_id=pool["record_id"].astype(str)).set_index("record_id")
    out = []
    for row in dev.to_dict("records"):
        record = pool.loc[row["record_id"]]
        out.append(GoldenExample(
            request=SupportRequest(request_id=row["dev_id"], brand=load_config()["brand"],
                                   customer_text=record["customer_text_clean"],
                                   context=tuple(Turn(role=str(t["role"]), text=str(t["text"]))
                                                 for t in record["context"]),
                                   is_followup=bool(record["is_followup"])),
            label_conversation_state=ConversationState(row["conversation_state"]),
            label_intent=Intent(row["intent"]) if row["intent"] else None,
            label_escalate=row["escalate"] == "yes",
            label_confidence=row["label_confidence"], slice="dev"))
    return out


def main() -> None:
    cfg = load_config()
    llm = build_deps(profile="eval", config=cfg).agent_llm
    examples = dev_examples()
    started = datetime.now(timezone.utc)

    rows, best, base_outputs = [], None, None
    for union in (False, True):
        for threshold in THRESHOLDS:
            run = run_agent(examples, llm, confidence_threshold=threshold, union_cues=union,
                            system="agent", sleep=0.5)
            if not run.complete:
                sys.exit(f"agent failed on {len(run.failures)} dev item(s): {run.failures[:3]}")
            m = evaluate(examples, run.outputs, "agent", n_boot=1000, seed=cfg["seed"]).metrics
            row = {"cues": "model+extractor" if union else "model only", "threshold": threshold,
                   "state_acc": m["state_accuracy"].value, "intent_f1": m["intent_macro_f1"].value,
                   "esc_precision": m["escalation_precision"].value,
                   "esc_recall": m["escalation_recall"].value,
                   "joint": m["joint_routing_correctness"].value,
                   "mean_latency_ms": sum(run.latencies_ms) / len(run.latencies_ms)}
            rows.append(row)
            if not union and threshold == THRESHOLDS[0]:
                base_outputs = run.outputs
            score = (row["joint"], row["esc_recall"])
            if best is None or score > (best["joint"], best["esc_recall"]):
                best = row

    table = pd.DataFrame(rows)
    lines = ["# Routing agent: confidence threshold and cue mode, chosen on dev", "",
             f"_Generated by `uv run python scripts/calibrate_agent_threshold.py` over "
             f"{len(examples)} dev items with `{llm.model}`, prompt `{CLASSIFIER_PROMPT_VERSION}`. "
             "The golden set is not loaded by this script. Classification is cached, so every row "
             "below re-runs only the deterministic policy step._", "",
             "Dev labels are ChatGPT drafts approved by the project owner, so dev numbers are a "
             "tuning signal, not a result.", "",
             "| cues | threshold | state acc | intent macro-F1 | esc P | esc R | joint | mean latency |",
             "|---|---|---|---|---|---|---|---|"]
    for row in rows:
        mark = " ←" if row is best else ""
        lines.append(f"| {row['cues']} | {row['threshold']:.1f} | {row['state_acc']:.2f} | "
                     f"{row['intent_f1']:.2f} | {row['esc_precision']:.2f} | {row['esc_recall']:.2f} | "
                     f"{row['joint']:.2f}{mark} | {row['mean_latency_ms']:.0f} ms |")
    # Is the threshold doing anything at all? Only if the model's confidence varies meaningfully.
    gold = {e.request.request_id: e for e in examples}
    scored = [(o.intent_confidence,
               o.conversation_state == gold[o.request_id].label_conversation_state
               and o.intent == gold[o.request_id].label_intent) for o in base_outputs]
    values = sorted({round(c, 2) for c, _ in scored})
    distinct = len(values)
    lines += ["", "## Does the confidence signal support a threshold at all?", "",
              f"The model reports {distinct} distinct confidence value(s) on dev: "
              f"{', '.join(f'{v:.2f}' for v in values)}.", "",
              "| confidence | items | state+intent correct |", "|---|---|---|"]
    for value in values:
        bucket = [ok for c, ok in scored if round(c, 2) == value]
        lines.append(f"| {value:.2f} | {len(bucket)} | {sum(bucket) / len(bucket):.2f} |")
    wrong_high = [c for c, ok in scored if not ok and round(c, 2) == max(values)]
    lines += ["", f"**{len(wrong_high)} of the model's errors carry its highest confidence value.** "
              "Self-reported confidence therefore does not separate correct from incorrect routing "
              "on dev, so policy rule (h) — escalate when confidence is low — has nothing to key on. "
              "Any threshold at or below the minimum observed value is inert; a threshold above it "
              "escalates the *most* confident items, which is worse than useless.", "",
              f"**Chosen: cues = {best['cues']}, threshold = {best['threshold']:.1f}** "
              "(highest joint routing on dev, escalation recall breaking ties). At this value rule "
              "(h) never fires, which is deliberate: the rule stays in the policy for a future "
              "confidence signal that actually carries information (token logprobs or "
              "self-consistency), to be developed on dev.", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")

    manifest = {"run": "agent_dev_calibration", "model": llm.model,
                "prompt_version": CLASSIFIER_PROMPT_VERSION, "items": len(examples),
                "thresholds_tried": THRESHOLDS, "cue_modes": ["model only", "model+extractor"],
                "chosen": {"cues": best["cues"], "threshold": best["threshold"]},
                "started_utc": started.isoformat(timespec="seconds"),
                "finished_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                "dev_labels": "ChatGPT-drafted, owner-approved: a tuning signal, not a result"}
    (OUT.parent / "agent_dev_calibration_run.json").write_text(json.dumps(manifest, indent=2) + "\n",
                                                               encoding="utf-8")
    print(table.to_string(index=False))
    print(f"\nchosen: cues={best['cues']} threshold={best['threshold']} -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
