"""Measure the deterministic cue extractor against the dev set's labelled cue columns.

Run from the repo root:   uv run python scripts/validate_cue_extractor.py

Dev is the tuning set: the extractor in `src/core/cues.py` may be refined against these numbers.
The golden set is never consulted here, and no cue labels are ever written to any evaluation file.

Writes results/eval/cue_extractor_dev.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from src.config import load_config, resolve  # noqa: E402
from src.contracts import SupportRequest, Turn  # noqa: E402
from src.core.cues import extract  # noqa: E402
from src.dataprep.loaders import eval_pool  # noqa: E402

OUT = ROOT / "results" / "eval" / "cue_extractor_dev.md"
# dev sheet column -> Cues field
COLUMNS = {"cue_strong_anger": "strong_anger", "cue_repeat_contact": "repeat_contact",
           "cue_steps_already_failed": "steps_failed",
           "cue_account_specific_action": "account_specific_action",
           "cue_prior_clarification": "prior_clarification",
           "cue_repair_or_replacement": "repair_or_replacement",
           "cue_account_compromised": "account_compromised", "cue_harm_or_legal": "harm_or_legal",
           "cue_money_dispute": "money_dispute"}


def dev_requests() -> list[tuple[dict, SupportRequest]]:
    dev = pd.read_csv(resolve("data/golden/dev_labeling_sheet.csv"), dtype=str, keep_default_na=False)
    pool = eval_pool()
    pool = pool.assign(record_id=pool["record_id"].astype(str)).set_index("record_id")
    out = []
    for row in dev.to_dict("records"):
        record = pool.loc[row["record_id"]]
        request = SupportRequest(
            request_id=row["dev_id"], brand=load_config()["brand"],
            customer_text=record["customer_text_clean"],
            context=tuple(Turn(role=str(t["role"]), text=str(t["text"])) for t in record["context"]),
            is_followup=bool(record["is_followup"]))
        out.append((row, request))
    return out


def main() -> None:
    rows = dev_requests()
    stats = {field: {"tp": 0, "fp": 0, "fn": 0, "gold": 0, "pred": 0} for field in COLUMNS.values()}
    misses: list[tuple[str, str, str]] = []
    for row, request in rows:
        cues, _ = extract(request)
        for column, field in COLUMNS.items():
            gold = row[column].strip().lower() == "yes"
            pred = getattr(cues, field)
            s = stats[field]
            s["gold"] += gold
            s["pred"] += pred
            s["tp"] += gold and pred
            s["fp"] += pred and not gold
            s["fn"] += gold and not pred
            if gold and not pred:
                misses.append((field, row["dev_id"], " ".join(request.customer_text.split())[:110]))

    lines = ["# Deterministic cue extractor vs the dev cue labels", "",
             f"_Generated by `uv run python scripts/validate_cue_extractor.py` over "
             f"{len(rows)} dev items. Dev is the tuning set; the golden set is not consulted, and no "
             "cue labels are written to any evaluation file._", "",
             "| cue | gold | predicted | TP | FP | FN | precision | recall |", "|---|---|---|---|---|---|---|---|"]
    total_tp = total_fp = total_fn = 0
    for field, s in stats.items():
        precision = s["tp"] / (s["tp"] + s["fp"]) if s["tp"] + s["fp"] else float("nan")
        recall = s["tp"] / (s["tp"] + s["fn"]) if s["tp"] + s["fn"] else float("nan")
        total_tp += s["tp"]; total_fp += s["fp"]; total_fn += s["fn"]
        fmt = lambda v: "–" if v != v else f"{v:.2f}"  # noqa: E731
        lines.append(f"| `{field}` | {s['gold']} | {s['pred']} | {s['tp']} | {s['fp']} | {s['fn']} | "
                     f"{fmt(precision)} | {fmt(recall)} |")
    micro_p = total_tp / (total_tp + total_fp) if total_tp + total_fp else float("nan")
    micro_r = total_tp / (total_tp + total_fn) if total_tp + total_fn else float("nan")
    lines += ["", f"**Micro-averaged: precision {micro_p:.2f}, recall {micro_r:.2f}** "
              f"({total_tp} true positives, {total_fp} false positives, {total_fn} misses).", "",
              "## Misses, item by item", "",
              "Some are genuine pattern gaps; others are dev labels that reach beyond the codebook "
              "definition (a refund how-to labelled `money_dispute`, for instance). Where they "
              "conflict, the frozen definition wins and the miss is accepted.", ""]
    for field, dev_id, text in misses:
        lines.append(f"- **{field}** · {dev_id}: {text}")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"micro precision {micro_p:.2f} | micro recall {micro_r:.2f} | misses {total_fn}")
    for field, s in stats.items():
        p = s["tp"] / (s["tp"] + s["fp"]) if s["tp"] + s["fp"] else float("nan")
        r = s["tp"] / (s["tp"] + s["fn"]) if s["tp"] + s["fn"] else float("nan")
        print(f"  {field:26s} gold={s['gold']:2d} pred={s['pred']:2d} P={p:.2f} R={r:.2f}")


if __name__ == "__main__":
    main()
